//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dobrofilm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dobrofilm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BaseImage {
            get {
                object obj = ResourceManager.GetObject("BaseImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema        
        ///    xmlns:mstns=&quot;http://tempuri.org/XMLSchema.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;categoris&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;category&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:simpleContent&gt;
        ///              &lt;xs:extension base=&quot;xs:string&quot;&gt;
        ///                &lt;xs:attribute name=&quot;id&quot; type=&quot;xs:integer&quot; use=&quot;required&quot; /&gt;
        ///                &lt;xs:attribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CategoryList {
            get {
                return ResourceManager.GetString("CategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crypted {
            get {
                object obj = ResourceManager.GetObject("Crypted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema    
        ///    xmlns:mstns=&quot;http://tempuri.org/XMLSchema.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;files&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;file&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:complexType&gt;           
        ///            &lt;xs:simpleContent&gt;
        ///              &lt;xs:extension base=&quot;xs:string&quot;&gt;
        ///                &lt;xs:attribute name=&quot;GUID&quot; type=&quot;xs:string&quot; use=&quot;required&quot; /&gt;
        ///                &lt;xs:attribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilmList {
            get {
                return ResourceManager.GetString("FilmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenOk {
            get {
                object obj = ResourceManager.GetObject("GreenOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Key {
            get {
                object obj = ResourceManager.GetObject("Key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema         
        ///    xmlns:mstns=&quot;http://tempuri.org/XMLSchema.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;links&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;link&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:simpleContent&gt;
        ///              &lt;xs:extension base=&quot;xs:string&quot;&gt;
        ///                &lt;xs:attribute name=&quot;GUIDFROM&quot; type=&quot;xs:string&quot;/&gt;
        ///                &lt;xs:attribute name =&quot;GUIDTO&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LinksList {
            get {
                return ResourceManager.GetString("LinksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotCrypted {
            get {
                object obj = ResourceManager.GetObject("NotCrypted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedX {
            get {
                object obj = ResourceManager.GetObject("RedX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema 
        ///    xmlns:mstns=&quot;http://tempuri.org/XMLSchema.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;FilmsScr&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;Screen&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:simpleContent&gt;
        ///              &lt;xs:extension base=&quot;xs:string&quot;&gt;
        ///                &lt;xs:attribute name=&quot;id&quot; type =&quot;xs:integer&quot;/&gt;
        ///                &lt;xs:attribute name=&quot;filmGuid&quot; type=&quot;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScreenList {
            get {
                return ResourceManager.GetString("ScreenList", resourceCulture);
            }
        }
    }
}
